image:
  name: ${CI_REGISTRY}/pd/do/images/base/production:latest
  entrypoint: ["/bin/bash", "-c"]

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

variables:
  CXXNAME: "GCC"
  CXXVERSION: "7.3.0"
  BUILD_JOBS: "8"
  TEST_JOBS: "8"

stages:
  - build

.prepare-environment: &prepare-environment
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_DEFAULT_BRANCH
    - export NCBI=/netopt/ncbi_tools64
    - source ncbi-facilities-switch.sh conan 1.53
    - export CONAN_USER_HOME=${CI_PROJECT_DIR}
    - echo ${CI_MERGE_REQUEST_EVENT_TYPE}
    - if [ "${WITHDEBUG}" = "--with-debug" ]; then DEBUGNAME="Debug"; fi
    - if [ "${WITHDLL}" = "--with-dll" ]; then DLLNAME="DLL"; fi
    - CXXVER=`echo ${CXXVERSION} | tr -d '.'`
    - SUFFIX=${WITHDLL}${WITHDEBUG}
    - BUILDDIR="CMake-${CXXNAME}${CXXVER}-${DEBUGNAME}${DLLNAME}/build"

merge-default:
  stage: build
  tags:
    - toolkit
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "merge-default"
    - DEBUGNAME="Release"
    - WITHDEBUG="--without-debug"
    - WITHDLL="--without-dll"
    - DLLNAME=""
    - *prepare-environment
    - ./cmake-configure ${CXXNAME} ${CXXVERSION} ${WITHDEBUG} ${WITHDLL} --with-targets=xncbi 2>&1 | tee "${CI_PROJECT_DIR}/config${SUFFIX}.log"
    - cd ${BUILDDIR}
    - make -j ${BUILD_JOBS} 2>&1 | tee "${CI_PROJECT_DIR}/build${SUFFIX}.log"
#    - export CTEST_PARALLEL_LEVEL=${TEST_JOBS}
#    - make test 2>&1 | tee "${CI_PROJECT_DIR}/test${SUFFIX}.log" || true
  artifacts:
    paths:
      - config${WITHDLL}${WITHDEBUG}.log
      - build${WITHDLL}${WITHDEBUG}.log
      - test${WITHDLL}${WITHDEBUG}.log


merge-stable:
  stage: build
  tags:
    - toolkit
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^stable/
  script:
    - echo "merge-stable"
    - DEBUGNAME="Release"
    - WITHDEBUG="--without-debug"
    - WITHDLL="--without-dll"
    - DLLNAME=""
    - *prepare-environment
    - ./cmake-configure ${CXXNAME} ${CXXVERSION} ${WITHDEBUG} ${WITHDLL} 2>&1 | tee "${CI_PROJECT_DIR}/config${SUFFIX}.log"
    - cd ${BUILDDIR}
    - make -j ${BUILD_JOBS} 2>&1 | tee "${CI_PROJECT_DIR}/build${SUFFIX}.log"
    - export CTEST_PARALLEL_LEVEL=${TEST_JOBS}
    - make test 2>&1 | tee "${CI_PROJECT_DIR}/test${SUFFIX}.log" || true
  artifacts:
    paths:
      - config${WITHDLL}${WITHDEBUG}.log
      - build${WITHDLL}${WITHDEBUG}.log
      - test${WITHDLL}${WITHDEBUG}.log
